# Delay before the servers stops in minutes
stop_delay: 1

# Command used to stop servers
# Do not change unless you know what you're doing
# Useful in case you start servers in a detached screen
stop_command: "stop\n"  # For the \n to work, must be between quotes ""

# Amount of servers that the plugin can start
# Set to <= 0 for no limit
max_servers: 1

# Enable HTTP server to manage the servers
# Set to <= 0 to disable
http_port: -1

# Syntax: [server name]: [command to start the server]
servers:
  # This is an example for a server named "lobby" hosted on the same Windows machine as the proxy
  test:
    directory: '/servers/test'
    jar_file: 'paper.jar'

    # Optional, maximum memory in MB
    maximum_memory: 8192

    # Optional minimum memory in MB
    minimum_memory: 2048

    # Optional, custom JVM arguments
    jvm_arguments: '-ThisIsAFlag'

    # Optional, setting this parameter to true will bypass the start cooldown of the server when using an old version of spigot.
    # Works only for Spigot and its derivatives
    IReallyKnowWhatIAmDoingISwear: true