# Delay before the servers stops in minutes
stop_delay: 1

# Command used to stop servers
# Do not change unless you know what you're doing
# Useful in case you start servers in a detached screen
stop_command: "stop\n"  # For the \n to work, must be between quotes ""

# Amount of servers that the plugin can start
# Set to <= 0 for no limit
max_servers: 1


# Syntax: [server name]: [command to start the server]
servers:
  # This is an example for a server named "lobby" hosted on the same Windows machine as the proxy
  lobby: 'cmd /k cd "C:\Servers\test" && start.bat'
    # The start.bat file:

    # java -jar -Xmx8G paper.jar nogui

  # Second example on Windows
  test1: '"C:\Servers\test\start.bat"'
    # The start.bat file:

    # cd "%~dp0" && java -Xmx8G -jar -DIReallyKnowWhatIAmDoingISwear paper.jar nogui

  # Example on Linux
  test2: 'sh /Servers/test/start.sh' # The path must be an absolute path
    # The script.sh must contain a cd command to the location of the server
    # Shell script example:

    # cd /Servers/test/
    # java -Xmx8G -jar -DIReallyKnowWhatIAmDoingISwear paper.jar nogui

  # TODO: Example on distant server