# Message send to a player trying to switch to a stopped server
redirect_message: 'Server is starting, you''ll be automatically redirected.'

# Message to send when a non-connected player tries to connect to a non-started server
kick_message: 'Server is starting, retry in a few seconds.'

# Delay before the servers stops in minutes
stop_delay: 1

servers:
  # This is an example for a server hosted on the same Windows machine under the port 25564
  - address: 'localhost/127.0.0.1:25564'
    command: 'cmd /k cd "C:\Servers\test" && start.bat'
  # TODO: Example on Linux to a distant server